# Generated by Django 5.0.3 on 2024-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='Student.student'),
        ),
    ]
