# Generated by Django 5.0.3 on 2024-03-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students_photos/')),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('religion', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('disability', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
