# Generated by Django 5.0.3 on 2024-04-03 10:58

import Student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Student.models.student_directory_path),
        ),
    ]
