# Generated by Django 5.0.3 on 2024-03-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='department',
            new_name='department_id',
        ),
    ]
